jwt:
  secret:
    access: ${ACCESS_TOKEN_SECRET}
    refresh: ${REFRESH_TOKEN_SECRET}

spring:
  application:
    name: AuthService

  datasource:
    driver-class-name: org.postgresql.Driver
    password: test_pass
    url: jdbc:postgresql://localhost:5432/user_db
    username: test_user

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: ${PORT:8080}
